"""
AXIOM Repo Reorganizer — v1.8.7
================================
Moves files into the target structure, updates imports, patches parser.

Usage:
    python reorganize.py --dry-run     # preview every planned action
    python reorganize.py               # execute
"""

import os
import re
import sys
import shutil
import subprocess
import argparse
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

ROOT = Path(__file__).parent
DRY_RUN = False

# ── Helpers ──────────────────────────────────────────────────────────────────

def echo(msg):
    print(msg)

def git_mv(src: Path, dst: Path):
    """Move a file using git mv so history is preserved."""
    dst.parent.mkdir(parents=True, exist_ok=True)
    if DRY_RUN:
        echo(f"  git mv  {src.relative_to(ROOT)}  -> {dst.relative_to(ROOT)}")
        return
    result = subprocess.run(
        ["git", "mv", str(src), str(dst)],
        cwd=ROOT, capture_output=True, text=True
    )
    if result.returncode != 0:
        echo(f"  [warn] git mv failed ({result.stderr.strip()}), using shutil")
        shutil.move(str(src), str(dst))

def git_rm(path: Path):
    """Remove a file from git tracking and disk."""
    if DRY_RUN:
        echo(f"  git rm  {path.relative_to(ROOT)}")
        return
    subprocess.run(["git", "rm", "-f", str(path)], cwd=ROOT, capture_output=True)

def write_file(path: Path, content: str):
    if DRY_RUN:
        echo(f"  write   {path.relative_to(ROOT)}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")

def patch_file(path: Path, old: str, new: str, description: str):
    """Replace old with new in file, in-place."""
    if DRY_RUN:
        echo(f"  patch   {path.relative_to(ROOT)}  [{description}]")
        return
    text = path.read_text(encoding="utf-8")
    if old not in text:
        echo(f"  [skip]  patch not needed in {path.relative_to(ROOT)}  [{description}]")
        return
    path.write_text(text.replace(old, new), encoding="utf-8")
    echo(f"  patched {path.relative_to(ROOT)}  [{description}]")

def make_init(path: Path, exports: list[str] = None):
    """Create a __init__.py for a new subpackage."""
    content = '"""AXIOM subpackage — auto-generated by reorganize.py"""\n'
    if exports:
        for e in exports:
            content += f"{e}\n"
    write_file(path, content)

# ── Section 1: axiom_constitutional/guards/ ──────────────────────────────────

GUARD_FILES = [
    "axiom_agency_guard.py",
    "axiom_destructive_guard.py",
    "axiom_guard_api.py",
    "axiom_injection_guard.py",
    "axiom_pii_guard.py",
    "axiom_review_queue.py",
    "axiom_security_guards.py",
]

# Root-level duplicates of the guard files (originals — can be removed after
# the package copies are canonical)
ROOT_GUARD_DUPLICATES = GUARD_FILES  # same names at root level

def move_guards():
    echo("\n[1/8] Guards ->axiom_constitutional/guards/")
    guards_dir = ROOT / "axiom_constitutional" / "guards"

    for name in GUARD_FILES:
        src = ROOT / "axiom_constitutional" / name
        dst = guards_dir / name
        if src.exists():
            git_mv(src, dst)
        else:
            echo(f"  [skip] {src.relative_to(ROOT)} not found")

    # Create guards/__init__.py that re-exports everything for backwards compat
    init_content = '"""AXIOM security guards subpackage."""\n'
    init_content += 'from axiom_constitutional.guards.axiom_destructive_guard import DestructiveOperationGuard\n'
    init_content += 'from axiom_constitutional.guards.axiom_pii_guard import PIIGuard\n'
    init_content += 'from axiom_constitutional.guards.axiom_injection_guard import OutputInjectionGuard\n'
    init_content += 'from axiom_constitutional.guards.axiom_agency_guard import AgencyGuard\n'
    init_content += 'from axiom_constitutional.guards.axiom_review_queue import ReviewQueue\n'
    init_content += 'from axiom_constitutional.guards.axiom_guard_api import app as guard_app\n'
    write_file(guards_dir / "__init__.py", init_content)

    # Delete root-level duplicate guard files
    echo("\n  Removing root-level guard duplicates...")
    for name in ROOT_GUARD_DUPLICATES:
        path = ROOT / name
        if path.exists():
            git_rm(path)

def patch_guard_imports():
    echo("\n  Patching guard imports in package files...")

    OLD_PREFIX = "from axiom_constitutional.axiom_"
    NEW_PREFIX = "from axiom_constitutional.guards.axiom_"

    targets = [
        ROOT / "axiom_constitutional" / "__init__.py",
        ROOT / "axiom_constitutional" / "client.py",
        ROOT / "axiom_constitutional" / "certifier.py",
        ROOT / "axiom_certify.py",
        ROOT / "cli.py",
    ]
    for path in targets:
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8") if not DRY_RUN else ""
        guard_names = [n.replace(".py", "") for n in GUARD_FILES]
        needs_patch = any(
            f"from axiom_constitutional.{g}" in (text if not DRY_RUN else "x")
            for g in guard_names
        )
        if DRY_RUN or needs_patch:
            for name in guard_names:
                patch_file(
                    path,
                    f"from axiom_constitutional.{name} import",
                    f"from axiom_constitutional.guards.{name} import",
                    f"guard import: {name}",
                )

    # Fix self-import in axiom_review_queue.py (used in __main__ block)
    rq_path = ROOT / "axiom_constitutional" / "guards" / "axiom_review_queue.py"
    if rq_path.exists() or DRY_RUN:
        patch_file(
            rq_path,
            "from axiom_review_queue import ReviewRouter",
            "from axiom_constitutional.guards.axiom_review_queue import ReviewRouter",
            "review_queue self-import",
        )

# ── Section 2: axiom_files/research/ ─────────────────────────────────────────

RESEARCH_AXIOM_FILES = [
    "research_critic.axiom",
    "research_data.axiom",
    "research_ethics.axiom",
    "research_experiment.axiom",
    "research_hypothesis.axiom",
    "research_literature.axiom",
    "research_report.axiom",
    "research_safety.axiom",
    "research_simulation.axiom",
]

def move_research_axioms():
    echo("\n[2/8] Research axioms ->axiom_files/research/")
    src_dir = ROOT / "axiom_files"
    dst_dir = ROOT / "axiom_files" / "research"

    for name in RESEARCH_AXIOM_FILES:
        src = src_dir / name
        dst = dst_dir / name
        if src.exists():
            git_mv(src, dst)
        else:
            echo(f"  [skip] {src.relative_to(ROOT)} not found")

def patch_research_pipeline():
    """Update axiom_research_pipeline.py AGENTS dict to reference research/ subdir."""
    echo("\n  Patching axiom_research_pipeline.py AGENTS paths...")
    pipeline = ROOT / "axiom_research_pipeline.py"
    if not pipeline.exists():
        return
    for name in RESEARCH_AXIOM_FILES:
        patch_file(
            pipeline,
            f'"{name}"',
            f'"research/{name}"',
            f"research axiom path: {name}",
        )

# ── Section 3: axiom_files/core/ ─────────────────────────────────────────────

# All .axiom files in axiom_files/ root that are not research_* and not in domains/
CORE_AXIOM_FILES = [
    "agent_factory.axiom",
    "bestfriend.axiom",
    "callguard.axiom",
    "composition_graph.axiom",
    "concepts.axiom",
    "controller_mapper.axiom",
    "conversation_monitor.axiom",
    "doctor.axiom",
    "dos_watcher.axiom",
    "efficiency.axiom",
    "electionguard.axiom",
    "evaluator.axiom",
    "friend.axiom",
    "game_watcher.axiom",
    "mom.axiom",
    "operator.axiom",
    "patient.axiom",
    "pattern_agent.axiom",
    "reader.axiom",
    "reasoner.axiom",
    "retailwatcher.axiom",
    "retriever.axiom",
    "reward_analysis.axiom",
    "rewriter.axiom",
    "rewriter_rubric.axiom",
    "sandbox.axiom",
    "sandbox_content.axiom",
    "sandbox_worker.axiom",
    "scout.axiom",
    "session.axiom",
    "shared_memory.axiom",
    "skill_builder.axiom",
    "teacher.axiom",
    "verifier.axiom",
    "worker.axiom",
]

def move_core_axioms():
    echo("\n[3/8] Core axioms ->axiom_files/core/")
    src_dir = ROOT / "axiom_files"
    dst_dir = ROOT / "axiom_files" / "core"

    for name in CORE_AXIOM_FILES:
        src = src_dir / name
        dst = dst_dir / name
        if src.exists():
            git_mv(src, dst)
        else:
            echo(f"  [skip] {src.relative_to(ROOT)} not found")

def patch_parser_subdir_search():
    """Patch axiom_files/parser.py to search core/ and research/ subdirs."""
    echo("\n  Patching axiom_files/parser.py for subdir search...")
    parser_path = ROOT / "axiom_files" / "parser.py"
    if not parser_path.exists():
        echo("  [skip] parser.py not found")
        return

    helper = '''
def _resolve_axiom_path(agent_name: str) -> str:
    """Resolve agent name to .axiom path, searching core/ and research/ subdirs."""
    base = agent_name.lower()
    # Strip subdir prefix if already included (e.g. "core/worker" -> "worker")
    if "/" in base:
        rel = base
        path = os.path.join(AXIOM_DIR, f"{rel}.axiom")
        if os.path.exists(path):
            return path
        # Try as-is without extension
        if os.path.exists(os.path.join(AXIOM_DIR, rel)):
            return os.path.join(AXIOM_DIR, rel)
    candidates = [
        os.path.join(AXIOM_DIR, f"{base}.axiom"),
        os.path.join(AXIOM_DIR, "core", f"{base}.axiom"),
        os.path.join(AXIOM_DIR, "research", f"{base}.axiom"),
    ]
    for p in candidates:
        if os.path.exists(p):
            return p
    return candidates[0]  # caller handles missing file

'''

    insert_marker = "AXIOM_DIR = os.environ.get"
    if DRY_RUN:
        echo(f"  patch   {parser_path.relative_to(ROOT)}  [add _resolve_axiom_path helper]")
        echo(f"  patch   {parser_path.relative_to(ROOT)}  [replace os.path.join(AXIOM_DIR, ...) calls]")
        return

    text = parser_path.read_text(encoding="utf-8")

    # Only inject if not already present
    if "_resolve_axiom_path" not in text:
        # Insert helper after the AXIOM_DIR = ... line
        idx = text.find(insert_marker)
        if idx != -1:
            end_of_line = text.index("\n", idx) + 1
            text = text[:end_of_line] + helper + text[end_of_line:]

    # Replace all os.path.join(AXIOM_DIR, f"{X.lower()}.axiom") patterns
    # with _resolve_axiom_path(X)
    pattern = re.compile(
        r'os\.path\.join\(AXIOM_DIR,\s*f"\{([^}]+?)\.lower\(\)\}\.axiom"\)'
    )
    text = pattern.sub(r'_resolve_axiom_path(\1)', text)

    # Also replace Path(AXIOM_DIR) / f"{X}.axiom" patterns (used in a few places)
    pattern2 = re.compile(
        r'Path\(AXIOM_DIR\)\s*/\s*f"\{([^}]+?)\.lower\(\)\}\.axiom"'
    )
    text = pattern2.sub(r'Path(_resolve_axiom_path(\1))', text)

    parser_path.write_text(text, encoding="utf-8")
    echo(f"  patched {parser_path.relative_to(ROOT)}  [subdir search]")

# ── Section 4: gamewatcher/chess/ and gamewatcher/pacman/ ────────────────────

CHESS_FILES_FROM_GW_DIR = [
    "gamewatcher.py",
    "browser_watcher.py",
]

PACMAN_FILES = [
    "browser_watcher.py",
    "layers.py",
    "pacman_watcher.py",
]

CHESS_ROOT_FILES = [
    ("gamewatcher.py",   "gamewatcher_chess.py"),
    ("player.axiom",     "player.axiom"),
    ("watcher.axiom",    "watcher.axiom"),
    ("evaluator.axiom",  "evaluator.axiom"),
]

def move_gamewatcher():
    echo("\n[4/8] Gamewatcher ->gamewatcher/chess/ + gamewatcher/pacman/")

    chess_dir  = ROOT / "gamewatcher" / "chess"
    pacman_dir = ROOT / "gamewatcher" / "pacman"

    # gamewatcher/*.py ->gamewatcher/chess/
    for name in CHESS_FILES_FROM_GW_DIR:
        src = ROOT / "gamewatcher" / name
        dst = chess_dir / name
        if src.exists():
            git_mv(src, dst)

    # pacman/*.py ->gamewatcher/pacman/
    for name in PACMAN_FILES:
        src = ROOT / "pacman" / name
        dst = pacman_dir / name
        if src.exists():
            git_mv(src, dst)

    # Root chess files
    for src_name, dst_name in CHESS_ROOT_FILES:
        src = ROOT / src_name
        dst = chess_dir / dst_name
        if src.exists():
            git_mv(src, dst)

    # __init__.py for chess and pacman
    make_init(chess_dir / "__init__.py")
    make_init(pacman_dir / "__init__.py")

# ── Section 5: docs/ ─────────────────────────────────────────────────────────

DOCS_FILES = [
    "AXIOM_DATA_GOVERNANCE.md.pdf",
    "AXIOM_OWASP_LLM_Compliance.pdf",
    "AXIOM_Progress_Report_April2026.pdf",
    "axiom_investor_deck.pdf",
    "axiom_spec_v1.3.pdf",
    "axiom_v1.4_when_changelog.pdf",
    "axiom_data_flow_demo.html",
    "axiom_landing.html",
]

def move_docs():
    echo("\n[5/8] Docs ->docs/")
    docs_dir = ROOT / "docs"

    for name in DOCS_FILES:
        src = ROOT / name
        dst = docs_dir / name
        if src.exists():
            git_mv(src, dst)
        else:
            echo(f"  [skip] {name} not found")

# ── Section 6: tests/ ────────────────────────────────────────────────────────

TESTS_FILES = [
    "acb_runner.py",
    "acb_scorer_test.py",
    "acb_submit.py",
    "acb_calibrated_system.txt",
    "acb_calibrated_weights.json",
    "acb_worker_185_system.txt",
    "callguard_test.py",
    "chaos_test_v1_0.py",
    "electionguard_test.py",
    "medical_test.py",
    "retailwatcher_test.py",
    "research_test.py",
    "test_validator_v1_8.py",
    "test axiom v1.3.py",
    "axiom_governance_test.py",
    "benchmark_v1_0.py",
    "benchmark_results_v1_0.json",
    "axiom_agi_eval_results.json",
    "axiom_agi_eval_reviewed.json",
    "axiom_model_comparison.json",
    "truthfulqa_results.json",
    "arc_agi_results.json",
    "rvl_results_hyp_01.json",
    "governance_test_results.json",
    "acb_leaderboard.json",
    "axiom_acb_manifest.json",
    "research_manifests.json",
]

def move_tests():
    echo("\n[6/8] Tests + results ->tests/")
    tests_dir = ROOT / "tests"

    for name in TESTS_FILES:
        src = ROOT / name
        dst = tests_dir / name
        if src.exists():
            git_mv(src, dst)
        else:
            echo(f"  [skip] {name} not found")

    make_init(tests_dir / "__init__.py")

# ── Section 7: examples/ ────────────────────────────────────────────────────

EXAMPLES_FILES = [
    "axiom_agi_eval.py",
    "axiom_arc_run.py",
    "axiom_humaneval_run.py",
    "research_rvl_run.py",
    "truthfulqa_run.py",
    "axiom_weight_balancer.py",
    "axiom_weight_compare.py",
    "call_manifest.py",
    "companion_manifest.py",
    "election_manifest.py",
    "medical_manifest.py",
    "research_manifest.py",
    "retail_manifest.py",
    "truthwatcher_manifest.py",
    "truthwatcher_url_test.py",
    "truthwatcher_test.py",
]

def move_examples():
    echo("\n[7/8] Examples ->examples/")
    examples_dir = ROOT / "examples"

    for name in EXAMPLES_FILES:
        src = ROOT / name
        dst = examples_dir / name
        if src.exists():
            git_mv(src, dst)
        else:
            echo(f"  [skip] {name} not found")

# ── Section 8: pyproject.toml package discovery update ───────────────────────

def patch_pyproject():
    echo("\n[8/8] Patching pyproject.toml package discovery...")
    pyproject = ROOT / "pyproject.toml"
    if not pyproject.exists():
        return
    patch_file(
        pyproject,
        'include = ["axiom_constitutional*", "axiom_files*"]',
        'include = ["axiom_constitutional*", "axiom_constitutional.guards*", "axiom_files*"]',
        "add guards subpackage to discovery",
    )

# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    global DRY_RUN
    parser = argparse.ArgumentParser(description="Reorganize axiom repo structure")
    parser.add_argument("--dry-run", action="store_true", help="Preview without making changes")
    args = parser.parse_args()
    DRY_RUN = args.dry_run

    if DRY_RUN:
        echo("=" * 60)
        echo("DRY RUN — no files will be modified")
        echo("=" * 60)
    else:
        echo("=" * 60)
        echo("EXECUTING reorganization...")
        echo("=" * 60)

    move_guards()
    patch_guard_imports()

    move_research_axioms()
    patch_research_pipeline()

    move_core_axioms()
    patch_parser_subdir_search()

    move_gamewatcher()
    move_docs()
    move_tests()
    move_examples()
    patch_pyproject()

    echo("\n" + "=" * 60)
    if DRY_RUN:
        echo("DRY RUN COMPLETE — run without --dry-run to execute")
    else:
        echo("DONE")
        echo("")
        echo("Next steps:")
        echo("  git add -A")
        echo('  git commit -m "refactor: clean repo structure v1.8.7 ..."')
        echo("  git push")
    echo("=" * 60)


if __name__ == "__main__":
    main()
