"""Tests for CognitiveGatingPipeline — the facade tying routing + intent +
HyDE + knowledge cookie into one retrieval flow."""
from __future__ import annotations

import os
from pathlib import Path

import pytest

os.environ.setdefault("AXIOM_MASTER_KEY", "e" * 64)

from axiom_cognitive_gating import CognitiveGatingPipeline, GatingTelemetry
from axiom_domain_ingester import DomainIngester
from axiom_domain_pack import DomainPackManifest, DomainPackStore, build_pack
from axiom_knowledge_cookie import KnowledgeCookieStore
from axiom_semantic_router import SemanticRouter


# ── fixtures ──────────────────────────────────────────────────────────────────

_DOMAINS = {
    "engineering": (
        "Stochastic residual dithering reduces quantization error variance "
        "across model weights at low bits-per-weight during inference. "
    ),
    "personal": (
        "To roast the vegetables for dinner preheat the oven and toss with "
        "olive oil. Best served warm with gravy on the side. "
    ),
}


@pytest.fixture
def store_dir(tmp_path: Path) -> Path:
    """Build + install two domain packs; return the store base dir."""
    base = tmp_path
    store = base / "store"
    for domain, text in _DOMAINS.items():
        idx = base / f"{domain}_idx"
        ing = DomainIngester(domain=domain, index_dir=idx, session_id="build")
        doc = base / f"{domain}.txt"
        doc.write_text(text * 15)
        ing.ingest_file(doc)
        m = DomainPackManifest(
            name=f"{domain}-pack", title=domain, description=domain,
            version="1.0.0", author="t", license="Apache-2.0", domain=domain)
        pack = build_pack(manifest=m, index_dir=idx, output_dir=base / "packs")
        DomainPackStore(base_dir=store).install(pack)
    return store


def _pipeline(store_dir: Path, tmp_path: Path, **kw) -> CognitiveGatingPipeline:
    store = DomainPackStore(base_dir=store_dir)
    router = SemanticRouter(store)
    router.build_indexes()
    kc = KnowledgeCookieStore(tmp_path / "kc.json")
    defaults = dict(router=router, domain_store=store, knowledge_store=kc,
                    enable_intent=True, session_id="sess-test")
    defaults.update(kw)
    return CognitiveGatingPipeline(**defaults)


# ── construction / introspection ────────────────────────────────────────────────

class TestConstruction:
    def test_empty_pipeline_not_active(self):
        g = CognitiveGatingPipeline()
        assert g.active is False
        assert g.layers() == ["intent"]  # intent is on by default, no router/kc/hyde

    def test_router_makes_active(self, store_dir, tmp_path):
        g = _pipeline(store_dir, tmp_path)
        assert g.active is True
        assert "router" in g.layers()
        assert "knowledge" in g.layers()

    def test_session_id_autogenerated(self):
        g = CognitiveGatingPipeline()
        assert g.session_id.startswith("sess-")
        assert len(g.session_id) > 8

    def test_explicit_session_id_used(self):
        g = CognitiveGatingPipeline(session_id="my-session")
        assert g.session_id == "my-session"

    def test_hyde_disabled_without_rewriter(self):
        g = CognitiveGatingPipeline(enable_hyde=True, rewriter=None)
        assert g.enable_hyde is False  # can't HyDE without a rewriter

    def test_intent_can_be_disabled(self, store_dir, tmp_path):
        g = _pipeline(store_dir, tmp_path, enable_intent=False)
        assert "intent" not in g.layers()


# ── routing ─────────────────────────────────────────────────────────────────────

class TestRouting:
    def test_engineering_query_routes_to_engineering(self, store_dir, tmp_path):
        g = _pipeline(store_dir, tmp_path)
        hits, tel = g.retrieve("how do I reduce quantization error in weights?", k=5)
        assert tel.routed_to == "engineering"

    def test_personal_query_routes_to_personal(self, store_dir, tmp_path):
        g = _pipeline(store_dir, tmp_path)
        hits, tel = g.retrieve("how long to roast vegetables for dinner?", k=5)
        assert tel.routed_to == "personal"

    def test_no_cross_domain_contamination(self, store_dir, tmp_path):
        g = _pipeline(store_dir, tmp_path)
        hits, tel = g.retrieve("quantization weight bits-per-weight inference", k=5)
        # every hit should come from the engineering pack index
        assert tel.routed_to == "engineering"
        assert all("personal" not in h.uri for h in hits)

    def test_routing_disabled_uses_fallback(self, tmp_path):
        class _FakeRetriever:
            def retrieve(self, q, *, k=5, domain=None, intent_filter=None):
                from axiom_research_retriever import RetrievedSource
                return [RetrievedSource(title="fb", uri="fallback/1", kind="x",
                                        score=1.0, snippet="fallback hit")]
        g = CognitiveGatingPipeline(fallback_retriever=_FakeRetriever())
        hits, tel = g.retrieve("anything", k=3)
        assert tel.routed_to == ""
        assert hits and hits[0].uri == "fallback/1"


# ── intent filtering ─────────────────────────────────────────────────────────────

class TestIntentFiltering:
    def test_intent_detected_for_procedure_query(self, store_dir, tmp_path):
        g = _pipeline(store_dir, tmp_path)
        _, tel = g.retrieve("how to fine-tune step by step", k=5)
        assert tel.intent_filter == "procedure"

    def test_general_query_no_intent_filter(self, store_dir, tmp_path):
        g = _pipeline(store_dir, tmp_path)
        _, tel = g.retrieve("tell me about model weights", k=5)
        # "general" intent maps to empty string (unfiltered)
        assert tel.intent_filter == ""

    def test_intent_filter_falls_back_when_empties_results(self, store_dir, tmp_path):
        # A procedure-intent query against a corpus with no procedure chunks
        # should still return hits (graceful fallback to unfiltered).
        g = _pipeline(store_dir, tmp_path)
        hits, tel = g.retrieve("how do I roast vegetables step by step?", k=5)
        assert tel.hits_returned > 0


# ── knowledge cookie wiring ──────────────────────────────────────────────────────

class TestKnowledgeRecording:
    def test_hits_recorded_into_cookie(self, store_dir, tmp_path):
        g = _pipeline(store_dir, tmp_path)
        _, tel = g.retrieve("quantization error reduction", k=5)
        assert tel.fragments_recorded > 0
        cookie = KnowledgeCookieStore(tmp_path / "kc.json").load()
        assert cookie is not None
        assert len(cookie.fragments) == tel.fragments_recorded

    def test_no_recording_without_cookie(self, store_dir, tmp_path):
        store = DomainPackStore(base_dir=store_dir)
        router = SemanticRouter(store); router.build_indexes()
        g = CognitiveGatingPipeline(router=router, domain_store=store,
                                    knowledge_store=None)
        _, tel = g.retrieve("quantization", k=5)
        assert tel.fragments_recorded == 0

    def test_cross_session_promotion(self, store_dir, tmp_path):
        kc_path = tmp_path / "kc.json"
        store = DomainPackStore(base_dir=store_dir)
        router = SemanticRouter(store); router.build_indexes()
        # Three distinct sessions hitting the same query → promotion at threshold 3
        for i in range(3):
            g = CognitiveGatingPipeline(
                router=router, domain_store=store,
                knowledge_store=KnowledgeCookieStore(kc_path),
                session_id=f"sess-{i}")
            g.retrieve("quantization error reduction in weights", k=5)
        final = CognitiveGatingPipeline(
            knowledge_store=KnowledgeCookieStore(kc_path), session_id="final")
        final.promote()
        ctx = final.extra_context()
        assert "hot_knowledge" in ctx

    def test_extra_context_empty_without_cookie(self):
        g = CognitiveGatingPipeline()
        assert g.extra_context() == {}

    def test_extra_context_empty_before_promotion(self, store_dir, tmp_path):
        g = _pipeline(store_dir, tmp_path)
        g.retrieve("quantization", k=5)  # one session, below threshold
        # single session → nothing promoted yet
        assert g.extra_context() == {}


# ── telemetry ─────────────────────────────────────────────────────────────────

class TestTelemetry:
    def test_telemetry_shape(self, store_dir, tmp_path):
        g = _pipeline(store_dir, tmp_path)
        _, tel = g.retrieve("quantization error", k=5)
        d = tel.to_dict()
        for key in ("routed_to", "intent_filter", "hyde_used", "hits_returned",
                    "fragments_recorded", "layers_active"):
            assert key in d

    def test_layers_active_recorded(self, store_dir, tmp_path):
        g = _pipeline(store_dir, tmp_path)
        _, tel = g.retrieve("quantization", k=5)
        assert "router" in tel.layers_active
        assert "knowledge" in tel.layers_active

    def test_candidates_counted_before_intent(self, store_dir, tmp_path):
        g = _pipeline(store_dir, tmp_path)
        _, tel = g.retrieve("how to fine-tune step by step", k=5)
        assert tel.candidates_before_intent >= tel.hits_returned


# ── HyDE expansion (mock backend) ───────────────────────────────────────────────

class _MockRewriter:
    """Stand-in QueryRewriter exposing rewrite_hyde()."""
    def __init__(self, answer: str = "", raise_err: bool = False):
        self._answer = answer
        self._raise = raise_err

    def rewrite_hyde(self, question, *, domain="general"):
        if self._raise:
            raise RuntimeError("backend down")
        return self._answer


class TestHyDE:
    def test_hyde_expands_query(self, store_dir, tmp_path):
        rw = _MockRewriter(answer="dense hypothetical answer with quantization "
                                  "residual dithering error variance vocabulary")
        g = _pipeline(store_dir, tmp_path, rewriter=rw, enable_hyde=True,
                      rewrite_domain="general")
        _, tel = g.retrieve("how to stop noise when shrinking weights", k=5)
        assert tel.hyde_used is True
        assert tel.hyde_source == "live-backend"
        assert "quantization" in tel.effective_query

    def test_hyde_falls_back_on_error(self, store_dir, tmp_path):
        rw = _MockRewriter(raise_err=True)
        g = _pipeline(store_dir, tmp_path, rewriter=rw, enable_hyde=True)
        _, tel = g.retrieve("how to shrink weights", k=5)
        assert tel.hyde_source == "fallback-original"
        assert tel.effective_query == "how to shrink weights"

    def test_hyde_falls_back_when_answer_equals_query(self, store_dir, tmp_path):
        rw = _MockRewriter(answer="how to shrink weights")  # identical → no expansion
        g = _pipeline(store_dir, tmp_path, rewriter=rw, enable_hyde=True)
        _, tel = g.retrieve("how to shrink weights", k=5)
        assert tel.hyde_used is False


# ── from_env wiring ─────────────────────────────────────────────────────────────

class TestFromEnv:
    def test_inactive_when_no_env(self, monkeypatch):
        for var in ("AXIOM_DOMAIN_STORE", "AXIOM_KNOWLEDGE_COOKIE", "AXIOM_HYDE"):
            monkeypatch.delenv(var, raising=False)
        g = CognitiveGatingPipeline.from_env()
        assert g.active is False

    def test_router_wired_from_env(self, store_dir, tmp_path, monkeypatch):
        monkeypatch.setenv("AXIOM_DOMAIN_STORE", str(store_dir))
        monkeypatch.delenv("AXIOM_KNOWLEDGE_COOKIE", raising=False)
        monkeypatch.delenv("AXIOM_HYDE", raising=False)
        g = CognitiveGatingPipeline.from_env()
        assert g.router is not None
        _, tel = g.retrieve("quantization weight inference", k=5)
        assert tel.routed_to == "engineering"

    def test_knowledge_wired_from_env(self, store_dir, tmp_path, monkeypatch):
        monkeypatch.setenv("AXIOM_DOMAIN_STORE", str(store_dir))
        monkeypatch.setenv("AXIOM_KNOWLEDGE_COOKIE", str(tmp_path / "envkc.json"))
        monkeypatch.delenv("AXIOM_HYDE", raising=False)
        g = CognitiveGatingPipeline.from_env()
        assert g.knowledge_store is not None
        _, tel = g.retrieve("quantization error", k=5)
        assert tel.fragments_recorded > 0

    def test_intent_disabled_via_env(self, store_dir, monkeypatch):
        monkeypatch.setenv("AXIOM_DOMAIN_STORE", str(store_dir))
        monkeypatch.setenv("AXIOM_GATING_INTENT", "0")
        g = CognitiveGatingPipeline.from_env()
        assert g.enable_intent is False


# ── robustness ───────────────────────────────────────────────────────────────────

class TestRobustness:
    def test_retrieve_never_raises_on_empty(self):
        g = CognitiveGatingPipeline()  # nothing wired
        hits, tel = g.retrieve("anything at all", k=5)
        assert hits == []
        assert tel.hits_returned == 0

    def test_empty_query_safe(self, store_dir, tmp_path):
        g = _pipeline(store_dir, tmp_path)
        hits, tel = g.retrieve("", k=5)
        assert isinstance(hits, list)

    def test_promote_safe_without_cookie(self):
        g = CognitiveGatingPipeline()
        g.promote()  # should not raise
